dist/modules/socket.js

room 입장 시 나를 제외한 사람에게 message를 보내기 위해 socket을 썼는데 front에서 메세지를 받을 수 없다고 해서 io로 수정했습니다.

Fix: socket에서 io로 수정

---

.gitignore
dist/controllers/paper.controller.js
dist/services/paper.service.js
models/tag.js
src/controllers/paper.controller.ts
src/services/paper.service.ts

Fix: 개인 페이지 조회 시 응답으로 보내는 컬럼들 추가

Feat: 글 작성 혹은 수정 시 태그, 카테고리 추가

---

dist/controllers/booking.controller.js
dist/routes/booking.route.js
dist/services/booking.service.js
models/booking.js

Fix: 예약테이블 코드 수정

---

dist/controllers/booking.controller.js
dist/routes/booking.route.js
dist/services/booking.service.js

Fix : 예약테이블 코드 수정

---

dist/controllers/booking.controller.js
models/index.js

Mj Chore : 예약테이블 코드 수정

---

dist/controllers/booking.controller.js

Chore : 코드 수정

---

dist/controllers/booking.controller.js
dist/services/booking.service.js

Fix :예외처리 1차 추가

---

dist/services/booking.service.js

Chore : 예약테이블 코드 수정

---

app.js
dist/modules/api_limiter.js
package-lock.json
package.json
src/modules/api_limiter.ts
tsconfig.json

express-rate-limit으로 시간당 요청 횟수 제한

Feat: 비정상적인 트래픽 제어

---

dist/controllers/booking.controller.js

Fix : dayjs timezone 설정

---

dist/controllers/booking.controller.js

Fix : dayjs timezone 추가설설정

---

dist/controllers/booking.controller.js

timezone 재설정

---

dist/controllers/booking.controller.js
package-lock.json
package.json

npm utc 설치, bookingController 타임존 재설정

npm utc 설치, bookingController 타임존 재설정

---

dist/controllers/booking.controller.js

Fix : bookingController 타임존 재설정

---

dist/controllers/booking.controller.js
dist/routes/booking.route.js
dist/services/booking.service.js

MJ Chore : 예약테이블 저장, list보기 수정

---

dist/controllers/booking.controller.js

Chore: 예약테이블 예약list 가져오기  수정

---

app.js
dist/controllers/paper.controller.js
dist/specs/paper.spec.js
models/user.js
src/controllers/paper.controller.ts

user 테이블 point defaultValue 10으로 변경

Feat: 테스트 케이스 추가 외 1건

---

dist/controllers/booking.controller.js
dist/specs/booking.spec.js

Fix:나뭇잎 음수처리 제한, booking 테스트코드시작

Fix:나뭇잎 음수처리 제한, booking 테스트코드시작

---

dist/controllers/booking.controller.js
dist/routes/booking.route.js
dist/services/booking.service.js
models/point.js

Chore: 예약테이블 삭제로직 수정

---

dist/controllers/booking.controller.js
dist/routes/booking.route.js
dist/services/booking.service.js

Chore : 예약테이블 수정

---

dist/controllers/paper.controller.js
dist/modules/date.js
dist/routes/paper.route.js
dist/services/paper.service.js
models/user.js
src/controllers/paper.controller.ts
src/modules/date.ts
src/routes/paper.route.ts
src/services/paper.service.ts
src/types/index.d.ts
src/types/paper.d.ts

Feat: 구독 중인 최신 게시글 조회 API 추가 외 1건

---

dist/controllers/booking.controller.js
dist/routes/booking.route.js
dist/services/booking.service.js

Chore : 예약테이블 나뭇잎 설정 로직 수정

---

dist/controllers/booking.controller.js
dist/services/booking.service.js

Fix : 예약테이블 나뭇잎 저장 로직 수정

---

dist/controllers/booking.controller.js
dist/services/booking.service.js
dist/services/user.service.js
models/booking.js
models/point.js
models/user.js

Fix : 예약테이블 관계설정 및 로직 추가

---

dist/controllers/booking.controller.js
dist/controllers/user.controller.js
dist/services/booking.service.js
dist/services/user.service.js

Fix: 예약테이블 로직 수정

---

dist/controllers/booking.controller.js

Fix: 예약테이블 나뭇잎 수정 로직 수정

---

dist/controllers/booking.controller.js
dist/services/booking.service.js

Fix: 예약테이블 예약 로직 수정

---

dist/controllers/booking.controller.js
dist/services/booking.service.js

Fix: 예약테이블 로직 수정 완료

---

dist/services/booking.service.js

Fix:나뭇잎 get요청 수정

---

dist/controllers/booking.controller.js

Fix: 예약시 예외처리 추가

---

dist/controllers/booking.controller.js
dist/routes/booking.route.js

Fix:예약테이블 로직 수정

---

dist/services/booking.service.js

Fix: 예약테이블 get요청 수정

---

app.js
dist/controllers/paper.controller.js
dist/modules/image_scheduler.js
dist/modules/view_count_scheduler.js
dist/services/paper.service.js
models/paper.js
src/controllers/paper.controller.ts
src/modules/image_scheduler.ts
src/modules/view_count_scheduler.ts
src/services/paper.service.ts
src/types/types.d.ts

redis로 일일 조회수 저장
node-cron으로 오전 12시에 총 조회수에 합산 및 일일 조회수 초기화

Feat: 게시글 조회수 로직 구현

---

app.js
dist/controllers/booking.controller.js
dist/modules/transfer.js

Fix: 예약 신청로직 수정

---

dist/controllers/paper.controller.js
dist/modules/image_scheduler.js
dist/modules/multer.js
dist/modules/view_count_scheduler.js
dist/services/paper.service.js
dist/specs/paper.spec.js
package-lock.json
package.json
src/controllers/paper.controller.ts
src/modules/image_scheduler.ts
src/modules/multer.ts
src/modules/view_count_scheduler.ts
src/services/paper.service.ts

마이피드 테스트 코드 추가 및 상세페이지 조회 테스트 코드 수정

Fix: winston 오류 수정 외 1건

---

dist/controllers/booking.controller.js

Fix:예약신청 코드 수정

---

dist/controllers/booking.controller.js
dist/services/booking.service.js

Fix: 예약신청 로직 수정

---

dist/services/paper.service.js
src/services/paper.service.ts

papers에 nickname, popularUsers에 introduction 추가

Fix: 메인페이지 API 응답값 수정(프론트 요청)

---

dist/controllers/booking.controller.js

Fix: 예약테이블 수정

---

dist/controllers/booking.controller.js

Fix: 예약 취소 로직 수정

---

dist/controllers/booking.controller.js
dist/services/booking.service.js

Fix: 언어 수정

---

dist/controllers/booking.controller.js
dist/services/booking.service.js

Fix: 예약로직 수정

---

dist/controllers/booking.controller.js

Fix:예약코드 수정

---

dist/controllers/booking.controller.js

Fix:오탈자 수정

---

dist/modules/validate_paper.js
dist/services/paper.service.js
dist/specs/paper.spec.js
models/user.js
src/modules/validate_paper.ts
src/services/paper.service.ts

메인 페이지 데이터 redis 업데이트 간격 10분으로 변경

Fix: 메인 페이지 조회 API 응답값 유저 순서 변경 외 1건

---

dist/modules/validate_paper.js
dist/services/paper.service.js
dist/specs/paper.spec.js
src/modules/validate_paper.ts
src/services/paper.service.ts

테스트용 DB 연결
예외 처리 케이스들 추가
게시글 삭제 시 버그 수정

Test: 테스트 코드 수정

---

app.js
dist/controllers/booking.controller.js
dist/specs/booking.spec.js

Chore : 불필요한 코드 삭제

---

dist/controllers/booking.controller.js

 Fix: 코드수정

---

dist/controllers/booking.controller.js

Fix: 예약제한 추가

---

dist/controllers/booking.controller.js

Fix : 코드 수정

---

dist/controllers/paper.controller.js
dist/routes/paper.route.js
dist/services/paper.service.js
dist/specs/paper.spec.js
src/controllers/paper.controller.ts
src/routes/paper.route.ts
src/services/paper.service.ts

모든 게시글 및 키워드 검색 응답 데이터 수정
카테고리 관련 API URL 수정

Feat: 카테고리 조회 API 추가 외 2건

---

dist/controllers/booking.controller.js
dist/services/booking.service.js
dist/specs/booking.spec.js

Chore:코드 부분수정 및 테스트코드 추가

---

dist/controllers/paper.controller.js
dist/services/paper.service.js
src/controllers/paper.controller.ts
src/services/paper.service.ts

개인 페이지 조회 시 팔로워 데이터 중 닉네임만 전송하도록 수정

Fix: 자기 글 좋아요 가능하게 수정 외 1건

---

dist/modules/multer.js
dist/services/paper.service.js
src/modules/multer.ts
src/services/paper.service.ts

개인 페이지 조회 API 응답 데이터에 팔로워 블로그 아이디 전송

Fix: 이미지 업로드 사이즈 조정 외 1건

---

dist/services/booking.service.js
models/user.js

Fix: 로직 수정

---

dist/routes/booking.route.js

Chore:오탈자 수정

---

dist/services/booking.service.js
models/booking.js
models/leaf.js
models/user.js

Fix: db관계설정 삭제 및 오탈자 개선

---

dist/controllers/booking.controller.js
dist/specs/booking.spec.js

test:testCode 완료

---

dist/modules/contents_preview.js
dist/modules/multer.js
src/modules/contents_preview.ts
src/modules/multer.ts

Fix: 내용 미리보기 글자수 변경 외 1건

---

dist/services/booking.service.js

Fix: 예약 로직 수정

---

dist/specs/booking.spec.js
package.json

test : testCode coverage 확인
